"""
agents/state.py
─────────────────────────────────────────────────────────────────────────────
Polymath.ai — Phase 3: Shared Graph State Schema

Defines `PolymathState`, the single TypedDict that flows through every node in
the LangGraph StateGraph.  Each node receives the full state and returns a
*partial* dict containing only the keys it modifies — LangGraph merges these
updates automatically.

Field contract
──────────────
question      Set once at graph entry; never mutated.
domain        Written by router_node; read by specialist nodes and edges.
context_docs  Written by the active specialist; raw LangChain Document objects.
answer        Written by the active specialist; the final model-generated text.
citations     Written by the active specialist; deduplicated "file p.N" strings.
agent_trace   Append-only audit log.  Uses `operator.add` as the LangGraph
              reducer, so every node that appends a string to a *new list*
              gets that list concatenated with the existing trace — not replaced.
─────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import operator
from typing import Annotated

from typing_extensions import TypedDict


class PolymathState(TypedDict):
    """Shared mutable state passed between every node in the orchestration graph."""

    # ── Input ─────────────────────────────────────────────────────────────
    question: str
    """The raw user question.  Set at graph entry; never overwritten."""

    # ── Routing ───────────────────────────────────────────────────────────
    domain: str
    """
    Domain label assigned by the Router Node.
    One of: 'compiler_theory' | 'algorithms' | 'theory_of_comp' | 'general_cs'
    """

    # ── Retrieval ─────────────────────────────────────────────────────────
    context_docs: list
    """
    Raw LangChain Document objects retrieved from ChromaDB by the active
    specialist.  Downstream nodes may read these for re-ranking or citation.
    """

    # ── Generation ────────────────────────────────────────────────────────
    answer: str
    """Final answer string generated by the active specialist agent."""

    citations: list[str]
    """
    Deduplicated source references in the format 'filename.pdf  (page N)'.
    Built by the specialist from `context_docs` metadata.
    """

    # ── Observability ─────────────────────────────────────────────────────
    agent_trace: Annotated[list[str], operator.add]
    """
    Ordered audit log of agent activity.  Each node appends one or more
    formatted strings.  The `operator.add` reducer instructs LangGraph to
    *concatenate* lists rather than replace the field, making every node's
    contribution permanently visible in the final state.

    Example entries:
        "[Router]   Classified → 'compiler_theory'  (confidence: 0.95)"
        "[Compiler] Retrieved 5 chunks from ChromaDB"
        "[Compiler] Answer generated in 1.83s"
    """
