"""
api/models.py
─────────────────────────────────────────────────────────────────────────────
Polymath.ai — Phase 4: API Pydantic Schemas

Defines the HTTP request and response models for the FastAPI layer, ensuring
strict validation of incoming payloads and clean structuring of outgoing data.
─────────────────────────────────────────────────────────────────────────────
"""

from typing import List

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """Payload for POST /query endpoint."""
    question: str = Field(
        ...,
        description="The computer science question to ask Polymath.",
        examples=["What is a control flow graph?"],
    )


class QueryResponse(BaseModel):
    """Structured JSON response returned by POST /query."""
    question: str = Field(
        ...,
        description="The original question.",
    )
    domain: str = Field(
        ...,
        description="The CS domain the router classified this query into.",
        examples=["compiler_theory"],
    )
    answer: str = Field(
        ...,
        description="The markdown-formatted answer generated by the agent.",
    )
    citations: List[str] = Field(
        default_factory=list,
        description="Deduplicated source document references.",
    )
    agent_trace: List[str] = Field(
        default_factory=list,
        description="Audit log of the path taken through the LangGraph.",
    )
    processing_time_sec: float = Field(
        ...,
        description="Total wall-clock time in seconds.",
    )


class ErrorResponse(BaseModel):
    """Standardised error response."""
    detail: str = Field(..., description="A description of what went wrong.")


class DocumentItem(BaseModel):
    """Metadata for an ingested document file."""
    filename: str = Field(..., description="Name of the PDF file.")
    chunks: int = Field(..., description="Number of text chunks indexed in ChromaDB.")


class QuizQuestion(BaseModel):
    id: int
    question: str
    options: List[str]
    answer_index: int
    explanation: str


class QuizRequest(BaseModel):
    domain: str = Field(default="general_cs", description="Domain for quiz generation.")


class QuizResponse(BaseModel):
    domain: str
    questions: List[QuizQuestion]


class FlashcardItem(BaseModel):
    id: int
    front: str
    back: str


class FlashcardRequest(BaseModel):
    domain: str = Field(default="general_cs", description="Domain or topic for flashcard generation.")


class FlashcardResponse(BaseModel):
    domain: str
    cards: List[FlashcardItem]
